/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./assets/models/site_builder_advert.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.089, -1, 0.096]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Case} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.CaseFront}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.StainlessSteel}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.BlackPlastic}
        position={[-0.089, -1, -0.024]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.BlackPlastic}
        position={[0.491, -1, -0.024]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[-0.089, -1, 0.096]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.CaseFront}
        />
      </group>
      <group position={[-0.016, 0.6, 0.096]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.CaseFront}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials.Case}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_3.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_4.geometry}
          material={materials.StainlessSteel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_5.geometry}
          material={materials.Screen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Disk}
        position={[1.3, -0.993, 1.1]}
        rotation={[-Math.PI, 0.151, -Math.PI]}
        scale={0.126}
      />
      <group position={[1.3, -0.993, 1.1]} rotation={[-Math.PI, 0.151, -Math.PI]} scale={0.126}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials.Disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials.Plastic}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Disk}
        position={[1.7, -0.99, 1.3]}
        rotation={[-Math.PI, 0.479, -Math.PI]}
        scale={0.126}
      />
      <group position={[1.7, -0.99, 1.3]} rotation={[-Math.PI, 0.479, -Math.PI]} scale={0.126}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials.Disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials.Plastic}
        />
      </group>
      <group position={[-1.301, -0.467, 0.883]} rotation={[Math.PI / 2, 0, -0.355]} scale={0.175}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_3.geometry}
          material={materials['Black Shiny Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_4.geometry}
          material={materials['Screen.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_5.geometry}
          material={materials['Red Plastic']}
        />
      </group>
      <group position={[1.653, -0.489, 0.184]} rotation={[0, -0.208, 0]} scale={0.511}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials['Black Plastic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_2.geometry}
          material={materials['Beige Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_3.geometry}
          material={materials['Red Plastic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_4.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_5.geometry}
          material={materials.Lens}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.CSharp}
        position={[0.995, -0.189, 0.679]}
        rotation={[1.904, 0.459, -1.249]}
        scale={0.233}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.CPP}
        position={[-0.56, -0.723, 1.406]}
        rotation={[1.107, -0.355, -0.342]}
        scale={0.238}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.TS}
        position={[0.962, -0.84, 1.599]}
        rotation={[Math.PI, -1.231, Math.PI]}
        scale={0.161}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.JS}
        position={[-0.076, 0.833, 0.319]}
        rotation={[-0.088, 0.466, 0]}
        scale={0.159}
      />
      <group
        position={[0.482, -0.974, 1.621]}
        rotation={[0, -Math.PI / 4, -Math.PI / 2]}
        scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials.Lead}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials.Handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_4.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_5.geometry}
          material={materials.Eraser}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.Disk}
        position={[-1.049, -0.768, 0.377]}
        rotation={[1.57, -0.41, 1.57]}
        scale={0.126}
      />
      <group position={[-1.049, -0.768, 0.377]} rotation={[1.57, -0.41, 1.57]} scale={0.126}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials.Disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials.Plastic}
        />
      </group>
      <group position={[-0.275, -0.422, -0.582]} rotation={[0, 0.151, -Math.PI / 2]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials.Lead}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials.Wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_3.geometry}
          material={materials.Handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_4.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_5.geometry}
          material={materials.Eraser}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/models/site_builder_advert.glb')

