/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./assets/models/language-stack.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.JS}
        position={[-0.492, 1.673, -1.401]}
        rotation={[-0.652, 0.637, 0.279]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.CPP}
        position={[-0.114, -0.709, 1.153]}
        rotation={[1.17, 0.475, -1.088]}
        scale={1.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.CSharp}
        position={[0.011, 0.627, 1.129]}
        rotation={[1.34, -0.096, -0.725]}
        scale={1.298}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.TS}
        position={[0.854, -1.03, -0.175]}
        rotation={[0.079, -0.603, 0.2]}
      />
    </group>
  );
}

useGLTF.preload("./assets/models/language-stack.glb");